CREATE TABLE IF NOT EXISTS `customerEvidenceDb`.`PHOTOS`
(
    `ID`      INT  NOT NULL AUTO_INCREMENT,
    `PICTURE` BLOB NULL,
    PRIMARY KEY (`ID`)
)
    ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `customerEvidenceDb`.`CUSTOMERS`
(
    `ID`          INT         NOT NULL AUTO_INCREMENT,
    `NAME`        VARCHAR(45) NOT NULL,
    `SURNAME`     VARCHAR(45) NOT NULL,
    `PHONE`       VARCHAR(45) NOT NULL,
    `EMAIL`       VARCHAR(45) NOT NULL,
    `FK_PHOTO_ID` INT         NOT NULL,
    PRIMARY KEY (`ID`),
    INDEX `fk_CUSTOMERS_PHOTOS1_idx` (`FK_PHOTO_ID` ASC) VISIBLE,
    CONSTRAINT `fk_CUSTOMERS_PHOTOS1`
        FOREIGN KEY (`FK_PHOTO_ID`)
            REFERENCES `customerEvidenceDb`.`PHOTOS` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `customerEvidenceDb`.`USERS`
(
    `ID`             INT         NOT NULL AUTO_INCREMENT,
    `USERNAME`       VARCHAR(45) NOT NULL,
    `PASSWORD`       VARCHAR(45) NOT NULL,
    `FK_CUSTOMER_ID` INT         NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE INDEX `USERNAME_UNIQUE` (`USERNAME` ASC) VISIBLE,
    INDEX `fk_USERS_CUSTOMERS1_idx` (`FK_CUSTOMER_ID` ASC) VISIBLE,
    CONSTRAINT `fk_USERS_CUSTOMERS1`
        FOREIGN KEY (`FK_CUSTOMER_ID`)
            REFERENCES `customerEvidenceDb`.`CUSTOMERS` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `customerEvidenceDb`.`ROLES`
(
    `ID`         INT         NOT NULL AUTO_INCREMENT,
    `NAME`       VARCHAR(45) NOT NULL,
    `FK_USER_ID` INT         NOT NULL,
    PRIMARY KEY (`ID`),
    INDEX `fk_ROLE_USERS1_idx` (`FK_USER_ID` ASC) VISIBLE,
    CONSTRAINT `fk_ROLE_USERS1`
        FOREIGN KEY (`FK_USER_ID`)
            REFERENCES `customerEvidenceDb`.`USERS` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `customerEvidenceDb`.`ORDERS`
(
    `ID`             INT           NOT NULL AUTO_INCREMENT,
    `PRICE`          DECIMAL(6, 2) NOT NULL,
    `PRICE_WITH_VAT` DECIMAL(6, 2) NOT NULL,
    `CREATED`        DATETIME      NOT NULL,
    `FK_CUSTOMER_ID` INT           NOT NULL,
    PRIMARY KEY (`ID`),
    INDEX `fk_ORDERS_CUSTOMERS1_idx` (`FK_CUSTOMER_ID` ASC) VISIBLE,
    CONSTRAINT `fk_ORDERS_CUSTOMERS1`
        FOREIGN KEY (`FK_CUSTOMER_ID`)
            REFERENCES `customerEvidenceDb`.`CUSTOMERS` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `customerEvidenceDb`.`PRODUCTS`
(
    `ID`             INT           NOT NULL AUTO_INCREMENT,
    `NAME`           VARCHAR(45)   NOT NULL,
    `DESCRIPTION`    VARCHAR(245)  NOT NULL,
    `CODE`           VARCHAR(45)   NOT NULL,
    `PRICE`          DECIMAL(6, 2) NOT NULL,
    `PRICE_WITH_VAT` DECIMAL(6, 2) NOT NULL,
    `FK_PHOTO_ID`    INT           NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE INDEX `CODE_UNIQUE` (`CODE` ASC) VISIBLE,
    INDEX `fk_PRODUCTS_PHOTOS1_idx` (`FK_PHOTO_ID` ASC) VISIBLE,
    CONSTRAINT `fk_PRODUCTS_PHOTOS1`
        FOREIGN KEY (`FK_PHOTO_ID`)
            REFERENCES `customerEvidenceDb`.`PHOTOS` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `customerEvidenceDb`.`ORDER_ITEM`
(
    `ID`             INT           NOT NULL AUTO_INCREMENT,
    `COUNT`          INT           NOT NULL,
    `FK_PRODUCT_ID`  INT           NOT NULL,
    `FK_ORDER_ID`    INT           NOT NULL,
    PRIMARY KEY (`ID`),
    INDEX `fk_ORDER_ITEM_PRODUCTS_idx` (`FK_PRODUCT_ID` ASC) VISIBLE,
    INDEX `fk_ORDER_ITEM_ORDERS1_idx` (`FK_ORDER_ID` ASC) VISIBLE,
    CONSTRAINT `fk_ORDER_ITEM_PRODUCTS`
        FOREIGN KEY (`FK_PRODUCT_ID`)
            REFERENCES `customerEvidenceDb`.`PRODUCTS` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_ORDER_ITEM_ORDERS1`
        FOREIGN KEY (`FK_ORDER_ID`)
            REFERENCES `customerEvidenceDb`.`ORDERS` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;