ALTER TABLE customerEvidenceDb.ORDERS ADD COLUMN VERSION int;

ALTER TABLE customerEvidenceDb.CUSTOMERS ADD COLUMN CREATED timestamp;
ALTER TABLE customerEvidenceDb.CUSTOMERS ADD COLUMN UPDATED timestamp;
ALTER TABLE customerEvidenceDb.CUSTOMERS ADD COLUMN VERSION int;

ALTER TABLE customerEvidenceDb.PRODUCTS ADD COLUMN CREATED timestamp;
ALTER TABLE customerEvidenceDb.PRODUCTS ADD COLUMN UPDATED timestamp;
ALTER TABLE customerEvidenceDb.PRODUCTS ADD COLUMN VERSION int;