version: "3"

services:
  db:
    image: mysql-customer-evidence:1.0.7
    container_name: mysql-customer-evidence
    ports:
      - "3307:3306"
  user-service:
    image: user-service-customer-evidence:1.0.7
    container_name: user-service-customer-evidence
    ports:
      - "8081:8080"
      - "4849:4848"
    depends_on:
      - db
  gateway:
    image: gateway-customer-evidence:1.0.15
    container_name: gateway-customer-evidence
    ports:
      - "8082:8080"
      - "4850:4848"
    depends_on:
      - db


